### ISSUE TITLE
Compatibility with M2.4.0

### ISSUE THREAD

**Issue by n2diving-dgx** [magetarian/customerTwoFactorAuth#64]
Fails to install with M2.4.0

$ composer require magetarian/module-customer-tfa

  [InvalidArgumentException]
  Package magetarian/module-customer-tfa at version  has a PHP requirement incompatible
   with your PHP version (7.4.8)

$ cat /etc/centos-release && /usr/local/apache/bin/httpd -v && mysql -V && php74 -v && php74 /usr/local/bin/composer -V && curl -s -XGET 'http://localhost:9200' | grep 'cluster_name\|number' |  xargs -n2 -d'\n'
CentOS Linux release 7.7.1908 (Core)
Server version: Apache/2.4.41 (Unix)
Server built:   Feb  4 2020 20:56:27
mysql  Ver 14.14 Distrib 5.7.29, for Linux (x86_64) using  EditLine wrapper
PHP 7.4.8 (cli) (built: Jul 30 2020 16:50:16) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.8, Copyright (c), by Zend Technologies
Composer version 1.10.5 2020-04-10 11:44:22
  "cluster_name" : "elasticsearch",     "number" : "7.8.0",

**Comment by sashas777** [comment]
Hi,
thanks for the report we working on the new release with support of Magento 2.4

**Comment by n2diving-dgx** [comment]
FYI.... attempt with --ignore-platform-reqs fails on 2.4 because msp/twofactorauth is no longer present, replaced by native module Magento/TwoFactorAuth

dotDEV:~/www/current$ php bin/magento --version
Magento CLI 2.4.0
dotDEV:~/www/current$ cat /etc/centos-release && /usr/local/apache/bin/httpd -v && mysql -V && php74 -v && php74 /usr/local/bin/composer -V && curl -s -XGET 'http://localhost:9200' | grep 'cluster_name\|number' |  xargs -n2 -d'\n'
CentOS Linux release 7.7.1908 (Core)
Server version: Apache/2.4.41 (Unix)
Server built:   Feb  4 2020 20:56:27
mysql  Ver 14.14 Distrib 5.7.29, for Linux (x86_64) using  EditLine wrapper
PHP 7.4.8 (cli) (built: Jul 30 2020 16:50:16) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.8, Copyright (c), by Zend Technologies
Composer version 1.10.5 2020-04-10 11:44:22
  "cluster_name" : "elasticsearch",     "number" : "7.8.0",
dotDEV:~/www/current$ composer require magetarian/module-customer-tfa --ignore-platform-reqs
Using version ^1.0 for magetarian/module-customer-tfa
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for bacon/bacon-qr-code (locked at 2.0.2) -> satisfiable by bacon/bacon-qr-code[2.0.2].
    - endroid/qr-code 2.5.0 requires bacon/bacon-qr-code ^1.0.3 -> satisfiable by bacon/bacon-qr-code[1.0.3].
    - endroid/qr-code 2.5.1 requires bacon/bacon-qr-code ^1.0.3 -> satisfiable by bacon/bacon-qr-code[1.0.3].
    - Conclusion: don't install magetarian/module-customer-tfa 1.0.2|install bacon/bacon-qr-code 1.0.3
    - Conclusion: don't install bacon/bacon-qr-code 1.0.3
    - magetarian/module-customer-tfa 1.0.0 requires msp/twofactorauth 3.1.* -> satisfiable by msp/twofactorauth[3.1.2, 3.1.1].
    - msp/twofactorauth 3.1.2 requires endroid/qr-code ^2.5 -> satisfiable by endroid/qr-code[2.5.0, 2.5.1].
    - msp/twofactorauth 3.1.1 requires endroid/qr-code ^2.5 -> satisfiable by endroid/qr-code[2.5.0, 2.5.1].
    - Installation request for magetarian/module-customer-tfa ^1.0 -> satisfiable by magetarian/module-customer-tfa[1.0.0, 1.0.2].


Installation failed, reverting ./composer.json to its original content.
dotDEV:~/www/current$

**Comment by sashas777** [comment]
@n2diving-dgx  
Hi,
The module updated to the version 1.1.0 which has Magento 2.4.x support.
