### ISSUE TITLE
Login does not work in popup in Magento 2.4.1

### ISSUE THREAD

**Issue by cundd** [magetarian/customerTwoFactorAuth#68]
**Describe the bug**
Login on domain.com/de/customer/account/login/ works great, but the login from within the popup (mini-cart "proceed to checkout" and cart "proceed to checkout") does not work (loader does not disappear).

**To Reproduce**
1. Install Magento 2.4.1
2. Add product to cart
3. Go to cart
4. Click on "proceed to checkout"
5. Wait for popup to open
6. Insert login data
7. Loader does not disappear

**Expected behavior**
Loader must disappear so I can click on "Login using Google Authenticator"

**Screenshots**
<img width="942" alt="Screenshot 2021-02-10 at 15 17 32" src="https://user-images.githubusercontent.com/743122/107536129-ba191c00-6bc1-11eb-8a94-fb358bcbbff0.png">

**Desktop:**
 - OS: macOS
 - Browser Chrome
 - Version 88.0.4324

**Smartphone:**
 - Device: iPhone6
 - OS: iOS12.5.1
 - Browser stock browser

**Additional context**
- Magento 2.4.1
- Guest checkout is disabled

**Comment by cundd** [comment]
And thank you for the work you put into this extension!

**Comment by atishgoswami** [comment]
Hi @cundd, thank you for reporting the detailed issue.
We are looking into it and get back to you as soon as we can

**Comment by sashas777** [comment]
Hi
@cundd  We added a new release 1.1.2 with the bugfix to this issue. please verify and re-open in case issue still persist.
Thank you

**Comment by cundd** [comment]
Thank you for the quick help! I will test it and give you feedback ASAP.
