### ISSUE TITLE
Providers are not shown in Authentication Popup on standard pages

### ISSUE THREAD

**Issue by cundd** [magetarian/customerTwoFactorAuth#71]
The list of providers is not rendered in the Authentication Popup on CMS or Catalog pages.

**Desktop:**
 - Device: MacBook Pro M1
 - OS: macOS 11.3
 - Browser Chrome
 - Version 90.0

**Additional context**
Guest checkout is disabled

**Comment by cundd** [comment]
The jsLayout XML to add children to the authenticationPopup is not always added to the layout. This could be done in the default.xml

**Comment by atishgoswami** [comment]
Thank you much for reporting the issue and providing the PRs for the fixes

@cundd you were own first external contributor to this project 😄
